name: Build Kaveri Map

on:
  push:
    paths:
      - 'data/**'
      - 'tei_mapping/*.py'
      - 'tei_mapping/static/**'

permissions:
  contents: write

jobs:
  build-map:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Python setup
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install pandas geopandas folium lxml beautifulsoup4

      # 4. Build the map
      - name: Build Kaveri map
        run: python tei_mapping/map_creator.py

      # 5. Deploy map to gh-pages
      - name: Publish map to generated branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tei_mapping/outputs
          publish_branch: generated
          force_orphan: true